version: '3'
networks:
  web:
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 3000:3000
    networks:
      - web
    environment:
      - API_URL=http://localhost/api
  backend:
    build:
      context: ../churrasco-garantido-node
      dockerfile: Dockerfile-dev
    networks:
      - web