version: '3'
networks:
  web:
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 3000:3000
    networks:
      - web
  backend:
    build:
      context: ../churrasco-garantido-node
      dockerfile: Dockerfile-dev
    ports:
      - 3001:3001
    networks:
      - web